# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PycharmProjects/SensoMatrix/ui/ecg_sim.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(868, 583)
        Dialog.setMinimumSize(QtCore.QSize(868, 583))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setMinimumSize(QtCore.QSize(394, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 392, 948))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.p_mag_label = QtWidgets.QLabel(self.groupBox)
        self.p_mag_label.setObjectName("p_mag_label")
        self.gridLayout.addWidget(self.p_mag_label, 0, 0, 1, 1)
        self.p_wid_label = QtWidgets.QLabel(self.groupBox)
        self.p_wid_label.setObjectName("p_wid_label")
        self.gridLayout.addWidget(self.p_wid_label, 0, 1, 1, 1)
        self.p_time_labe = QtWidgets.QLabel(self.groupBox)
        self.p_time_labe.setObjectName("p_time_labe")
        self.gridLayout.addWidget(self.p_time_labe, 0, 2, 1, 1)
        self.p_mag_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.p_mag_double_spinbox.setDecimals(3)
        self.p_mag_double_spinbox.setMinimum(0.1)
        self.p_mag_double_spinbox.setMaximum(0.3)
        self.p_mag_double_spinbox.setSingleStep(0.001)
        self.p_mag_double_spinbox.setProperty("value", 0.18)
        self.p_mag_double_spinbox.setObjectName("p_mag_double_spinbox")
        self.gridLayout.addWidget(self.p_mag_double_spinbox, 1, 0, 1, 1)
        self.p_wid_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.p_wid_double_spinbox.setDecimals(5)
        self.p_wid_double_spinbox.setMinimum(0.01)
        self.p_wid_double_spinbox.setMaximum(0.03)
        self.p_wid_double_spinbox.setSingleStep(0.0001)
        self.p_wid_double_spinbox.setProperty("value", 0.0178)
        self.p_wid_double_spinbox.setObjectName("p_wid_double_spinbox")
        self.gridLayout.addWidget(self.p_wid_double_spinbox, 1, 1, 1, 1)
        self.p_time_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.p_time_double_spinbox.setDecimals(4)
        self.p_time_double_spinbox.setMinimum(0.2)
        self.p_time_double_spinbox.setMaximum(0.3)
        self.p_time_double_spinbox.setSingleStep(0.0001)
        self.p_time_double_spinbox.setProperty("value", 0.2398)
        self.p_time_double_spinbox.setObjectName("p_time_double_spinbox")
        self.gridLayout.addWidget(self.p_time_double_spinbox, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.q1_mag_label = QtWidgets.QLabel(self.groupBox_2)
        self.q1_mag_label.setObjectName("q1_mag_label")
        self.gridLayout_2.addWidget(self.q1_mag_label, 0, 0, 1, 1)
        self.q1_wid_label = QtWidgets.QLabel(self.groupBox_2)
        self.q1_wid_label.setObjectName("q1_wid_label")
        self.gridLayout_2.addWidget(self.q1_wid_label, 0, 1, 1, 2)
        self.q1_time_labe = QtWidgets.QLabel(self.groupBox_2)
        self.q1_time_labe.setObjectName("q1_time_labe")
        self.gridLayout_2.addWidget(self.q1_time_labe, 0, 3, 1, 2)
        self.q1_mag_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.q1_mag_double_spinbox.setDecimals(4)
        self.q1_mag_double_spinbox.setMinimum(-0.2)
        self.q1_mag_double_spinbox.setMaximum(-0.1)
        self.q1_mag_double_spinbox.setSingleStep(0.001)
        self.q1_mag_double_spinbox.setProperty("value", -0.1103)
        self.q1_mag_double_spinbox.setObjectName("q1_mag_double_spinbox")
        self.gridLayout_2.addWidget(self.q1_mag_double_spinbox, 1, 0, 1, 1)
        self.q1_wid_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.q1_wid_double_spinbox.setDecimals(5)
        self.q1_wid_double_spinbox.setMinimum(0.025)
        self.q1_wid_double_spinbox.setMaximum(0.035)
        self.q1_wid_double_spinbox.setSingleStep(0.001)
        self.q1_wid_double_spinbox.setProperty("value", 0.03064)
        self.q1_wid_double_spinbox.setObjectName("q1_wid_double_spinbox")
        self.gridLayout_2.addWidget(self.q1_wid_double_spinbox, 1, 1, 1, 2)
        self.q1_time_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.q1_time_double_spinbox.setDecimals(4)
        self.q1_time_double_spinbox.setMinimum(0.25)
        self.q1_time_double_spinbox.setMaximum(0.35)
        self.q1_time_double_spinbox.setSingleStep(0.001)
        self.q1_time_double_spinbox.setProperty("value", 0.3218)
        self.q1_time_double_spinbox.setObjectName("q1_time_double_spinbox")
        self.gridLayout_2.addWidget(self.q1_time_double_spinbox, 1, 3, 1, 2)
        self.q2_mag_label = QtWidgets.QLabel(self.groupBox_2)
        self.q2_mag_label.setObjectName("q2_mag_label")
        self.gridLayout_2.addWidget(self.q2_mag_label, 2, 0, 1, 2)
        self.q2_wid_label = QtWidgets.QLabel(self.groupBox_2)
        self.q2_wid_label.setObjectName("q2_wid_label")
        self.gridLayout_2.addWidget(self.q2_wid_label, 2, 2, 1, 2)
        self.q2_time_label = QtWidgets.QLabel(self.groupBox_2)
        self.q2_time_label.setObjectName("q2_time_label")
        self.gridLayout_2.addWidget(self.q2_time_label, 2, 4, 1, 1)
        self.q2_mag_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.q2_mag_double_spinbox.setDecimals(4)
        self.q2_mag_double_spinbox.setMinimum(-0.15)
        self.q2_mag_double_spinbox.setMaximum(-0.05)
        self.q2_mag_double_spinbox.setSingleStep(0.001)
        self.q2_mag_double_spinbox.setProperty("value", -0.1075)
        self.q2_mag_double_spinbox.setObjectName("q2_mag_double_spinbox")
        self.gridLayout_2.addWidget(self.q2_mag_double_spinbox, 3, 0, 1, 2)
        self.q2_wid_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.q2_wid_double_spinbox.setDecimals(5)
        self.q2_wid_double_spinbox.setMinimum(0.005)
        self.q2_wid_double_spinbox.setMaximum(0.006)
        self.q2_wid_double_spinbox.setSingleStep(0.0001)
        self.q2_wid_double_spinbox.setProperty("value", 0.00571)
        self.q2_wid_double_spinbox.setObjectName("q2_wid_double_spinbox")
        self.gridLayout_2.addWidget(self.q2_wid_double_spinbox, 3, 2, 1, 2)
        self.q2_time_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.q2_time_double_spinbox.setDecimals(5)
        self.q2_time_double_spinbox.setMinimum(0.36)
        self.q2_time_double_spinbox.setMaximum(0.38)
        self.q2_time_double_spinbox.setSingleStep(0.001)
        self.q2_time_double_spinbox.setProperty("value", 0.37123)
        self.q2_time_double_spinbox.setObjectName("q2_time_double_spinbox")
        self.gridLayout_2.addWidget(self.q2_time_double_spinbox, 3, 4, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.r_mag_label = QtWidgets.QLabel(self.groupBox_3)
        self.r_mag_label.setObjectName("r_mag_label")
        self.gridLayout_3.addWidget(self.r_mag_label, 0, 0, 1, 1)
        self.r_wid_label = QtWidgets.QLabel(self.groupBox_3)
        self.r_wid_label.setObjectName("r_wid_label")
        self.gridLayout_3.addWidget(self.r_wid_label, 0, 1, 1, 1)
        self.r_time_label = QtWidgets.QLabel(self.groupBox_3)
        self.r_time_label.setObjectName("r_time_label")
        self.gridLayout_3.addWidget(self.r_time_label, 0, 2, 1, 1)
        self.r_mag_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.r_mag_double_spinbox.setDecimals(3)
        self.r_mag_double_spinbox.setMinimum(0.025)
        self.r_mag_double_spinbox.setMaximum(0.125)
        self.r_mag_double_spinbox.setSingleStep(0.001)
        self.r_mag_double_spinbox.setProperty("value", 0.05)
        self.r_mag_double_spinbox.setObjectName("r_mag_double_spinbox")
        self.gridLayout_3.addWidget(self.r_mag_double_spinbox, 1, 0, 1, 1)
        self.r_wid_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.r_wid_double_spinbox.setDecimals(5)
        self.r_wid_double_spinbox.setMinimum(0.029)
        self.r_wid_double_spinbox.setMaximum(0.031)
        self.r_wid_double_spinbox.setProperty("value", 0.02987)
        self.r_wid_double_spinbox.setObjectName("r_wid_double_spinbox")
        self.gridLayout_3.addWidget(self.r_wid_double_spinbox, 1, 1, 1, 1)
        self.r_time_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_3)
        self.r_time_double_spinbox.setDecimals(5)
        self.r_time_double_spinbox.setMinimum(0.46)
        self.r_time_double_spinbox.setMaximum(0.47)
        self.r_time_double_spinbox.setSingleStep(0.001)
        self.r_time_double_spinbox.setProperty("value", 0.46571)
        self.r_time_double_spinbox.setObjectName("r_time_double_spinbox")
        self.gridLayout_3.addWidget(self.r_time_double_spinbox, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.s_mag_label_2 = QtWidgets.QLabel(self.groupBox_4)
        self.s_mag_label_2.setObjectName("s_mag_label_2")
        self.gridLayout_4.addWidget(self.s_mag_label_2, 0, 0, 1, 1)
        self.s_wid_label = QtWidgets.QLabel(self.groupBox_4)
        self.s_wid_label.setObjectName("s_wid_label")
        self.gridLayout_4.addWidget(self.s_wid_label, 0, 1, 1, 1)
        self.s_time_label = QtWidgets.QLabel(self.groupBox_4)
        self.s_time_label.setObjectName("s_time_label")
        self.gridLayout_4.addWidget(self.s_time_label, 0, 2, 1, 1)
        self.s_mag_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.s_mag_double_spinbox.setDecimals(3)
        self.s_mag_double_spinbox.setMinimum(0.4)
        self.s_mag_double_spinbox.setMaximum(0.6)
        self.s_mag_double_spinbox.setSingleStep(0.001)
        self.s_mag_double_spinbox.setProperty("value", 0.509)
        self.s_mag_double_spinbox.setObjectName("s_mag_double_spinbox")
        self.gridLayout_4.addWidget(self.s_mag_double_spinbox, 1, 0, 1, 1)
        self.s_wid_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.s_wid_double_spinbox.setDecimals(5)
        self.s_wid_double_spinbox.setMinimum(0.008)
        self.s_wid_double_spinbox.setMaximum(0.01)
        self.s_wid_double_spinbox.setSingleStep(0.0001)
        self.s_wid_double_spinbox.setProperty("value", 0.00909)
        self.s_wid_double_spinbox.setObjectName("s_wid_double_spinbox")
        self.gridLayout_4.addWidget(self.s_wid_double_spinbox, 1, 1, 1, 1)
        self.s_time_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.s_time_double_spinbox.setDecimals(4)
        self.s_time_double_spinbox.setMinimum(0.46)
        self.s_time_double_spinbox.setMaximum(0.48)
        self.s_time_double_spinbox.setSingleStep(0.001)
        self.s_time_double_spinbox.setProperty("value", 0.4769)
        self.s_time_double_spinbox.setObjectName("s_time_double_spinbox")
        self.gridLayout_4.addWidget(self.s_time_double_spinbox, 1, 2, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.groupBox_5 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.t_time_label = QtWidgets.QLabel(self.groupBox_5)
        self.t_time_label.setObjectName("t_time_label")
        self.gridLayout_5.addWidget(self.t_time_label, 0, 2, 1, 1)
        self.t_mag_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.t_mag_double_spinbox.setDecimals(4)
        self.t_mag_double_spinbox.setMinimum(0.31)
        self.t_mag_double_spinbox.setMaximum(0.33)
        self.t_mag_double_spinbox.setSingleStep(0.001)
        self.t_mag_double_spinbox.setProperty("value", 0.3255)
        self.t_mag_double_spinbox.setObjectName("t_mag_double_spinbox")
        self.gridLayout_5.addWidget(self.t_mag_double_spinbox, 1, 0, 1, 1)
        self.t_wid_label = QtWidgets.QLabel(self.groupBox_5)
        self.t_wid_label.setObjectName("t_wid_label")
        self.gridLayout_5.addWidget(self.t_wid_label, 0, 1, 1, 1)
        self.t_wid_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.t_wid_double_spinbox.setDecimals(5)
        self.t_wid_double_spinbox.setMinimum(0.028)
        self.t_wid_double_spinbox.setMaximum(0.031)
        self.t_wid_double_spinbox.setSingleStep(0.0001)
        self.t_wid_double_spinbox.setProperty("value", 0.02978)
        self.t_wid_double_spinbox.setObjectName("t_wid_double_spinbox")
        self.gridLayout_5.addWidget(self.t_wid_double_spinbox, 1, 1, 1, 1)
        self.t_time_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.t_time_double_spinbox.setDecimals(4)
        self.t_time_double_spinbox.setMinimum(0.74)
        self.t_time_double_spinbox.setMaximum(0.76)
        self.t_time_double_spinbox.setSingleStep(0.001)
        self.t_time_double_spinbox.setObjectName("t_time_double_spinbox")
        self.gridLayout_5.addWidget(self.t_time_double_spinbox, 1, 2, 1, 1)
        self.t_mag_label = QtWidgets.QLabel(self.groupBox_5)
        self.t_mag_label.setObjectName("t_mag_label")
        self.gridLayout_5.addWidget(self.t_mag_label, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_5)
        self.groupBox_6 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_6.setObjectName("groupBox_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_6)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.period_label = QtWidgets.QLabel(self.groupBox_6)
        self.period_label.setObjectName("period_label")
        self.gridLayout_6.addWidget(self.period_label, 8, 0, 1, 1)
        self.noise_label = QtWidgets.QLabel(self.groupBox_6)
        self.noise_label.setObjectName("noise_label")
        self.gridLayout_6.addWidget(self.noise_label, 2, 0, 1, 1)
        self.simulation_line_edit = QtWidgets.QLineEdit(self.groupBox_6)
        self.simulation_line_edit.setObjectName("simulation_line_edit")
        self.gridLayout_6.addWidget(self.simulation_line_edit, 1, 0, 1, 1)
        self.duration_label = QtWidgets.QLabel(self.groupBox_6)
        self.duration_label.setObjectName("duration_label")
        self.gridLayout_6.addWidget(self.duration_label, 6, 0, 1, 1)
        self.duration_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.duration_spinbox.setMinimum(0.1)
        self.duration_spinbox.setMaximum(21600.0)
        self.duration_spinbox.setProperty("value", 0.9)
        self.duration_spinbox.setObjectName("duration_spinbox")
        self.gridLayout_6.addWidget(self.duration_spinbox, 7, 0, 1, 1)
        self.noise_double_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.noise_double_spinbox.setDecimals(3)
        self.noise_double_spinbox.setMaximum(100.0)
        self.noise_double_spinbox.setSingleStep(0.001)
        self.noise_double_spinbox.setObjectName("noise_double_spinbox")
        self.gridLayout_6.addWidget(self.noise_double_spinbox, 3, 0, 1, 1)
        self.sampling_frequency_label = QtWidgets.QLabel(self.groupBox_6)
        self.sampling_frequency_label.setObjectName("sampling_frequency_label")
        self.gridLayout_6.addWidget(self.sampling_frequency_label, 4, 0, 1, 1)
        self.signal_name_label = QtWidgets.QLabel(self.groupBox_6)
        self.signal_name_label.setObjectName("signal_name_label")
        self.gridLayout_6.addWidget(self.signal_name_label, 0, 0, 1, 1)
        self.period_spinbox = QtWidgets.QDoubleSpinBox(self.groupBox_6)
        self.period_spinbox.setDecimals(3)
        self.period_spinbox.setMinimum(0.1)
        self.period_spinbox.setMaximum(1.0)
        self.period_spinbox.setSingleStep(0.001)
        self.period_spinbox.setProperty("value", 0.9)
        self.period_spinbox.setObjectName("period_spinbox")
        self.gridLayout_6.addWidget(self.period_spinbox, 9, 0, 1, 1)
        self.sampling_frequency_spinbox = QtWidgets.QSpinBox(self.groupBox_6)
        self.sampling_frequency_spinbox.setMinimum(100)
        self.sampling_frequency_spinbox.setMaximum(1000)
        self.sampling_frequency_spinbox.setProperty("value", 256)
        self.sampling_frequency_spinbox.setObjectName("sampling_frequency_spinbox")
        self.gridLayout_6.addWidget(self.sampling_frequency_spinbox, 5, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_6)
        self.reset_signal_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.reset_signal_button.setAutoDefault(False)
        self.reset_signal_button.setObjectName("reset_signal_button")
        self.verticalLayout_2.addWidget(self.reset_signal_button)
        self.create_signal_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.create_signal_button.setObjectName("create_signal_button")
        self.verticalLayout_2.addWidget(self.create_signal_button)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.widget)
        self.graphicsView = PlotWidget(Dialog)
        self.graphicsView.setObjectName("graphicsView")
        self.horizontalLayout.addWidget(self.graphicsView)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "P Wave Parameters"))
        self.p_mag_label.setText(_translate("Dialog", "Magnitude"))
        self.p_wid_label.setText(_translate("Dialog", "Widthness"))
        self.p_time_labe.setText(_translate("Dialog", "Time"))
        self.groupBox_2.setTitle(_translate("Dialog", "Q Wave Parameters"))
        self.q1_mag_label.setText(_translate("Dialog", "Q1 Magnitude"))
        self.q1_wid_label.setText(_translate("Dialog", "Q1 Widthness"))
        self.q1_time_labe.setText(_translate("Dialog", "Q1 Time"))
        self.q2_mag_label.setText(_translate("Dialog", "Q2 Magnitude"))
        self.q2_wid_label.setText(_translate("Dialog", "Q2 Widthness"))
        self.q2_time_label.setText(_translate("Dialog", "Q2 Time"))
        self.groupBox_3.setTitle(_translate("Dialog", "R Wave Parameters"))
        self.r_mag_label.setText(_translate("Dialog", "Magnitude"))
        self.r_wid_label.setText(_translate("Dialog", "Widthness"))
        self.r_time_label.setText(_translate("Dialog", "Time"))
        self.groupBox_4.setTitle(_translate("Dialog", "S Wave Parameters"))
        self.s_mag_label_2.setText(_translate("Dialog", "Magnitude"))
        self.s_wid_label.setText(_translate("Dialog", "Widthness"))
        self.s_time_label.setText(_translate("Dialog", "Time"))
        self.groupBox_5.setTitle(_translate("Dialog", "T Wave Parameters"))
        self.t_time_label.setText(_translate("Dialog", "Time"))
        self.t_wid_label.setText(_translate("Dialog", "Widthness"))
        self.t_mag_label.setText(_translate("Dialog", "Magnitude"))
        self.groupBox_6.setTitle(_translate("Dialog", "Signal Properties"))
        self.period_label.setText(_translate("Dialog", "Period (s)"))
        self.noise_label.setText(_translate("Dialog", "Noise (Mean Value)"))
        self.simulation_line_edit.setPlaceholderText(_translate("Dialog", "ECG Simulation"))
        self.duration_label.setText(_translate("Dialog", "Duration (s)"))
        self.sampling_frequency_label.setText(_translate("Dialog", "Sampling Frequency"))
        self.signal_name_label.setText(_translate("Dialog", "Signal Name"))
        self.reset_signal_button.setText(_translate("Dialog", "Reset Signal"))
        self.create_signal_button.setText(_translate("Dialog", "Create Signal"))

from pyqtgraph import PlotWidget
