# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/eeg_sim.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(974, 559)
        Dialog.setMinimumSize(QtCore.QSize(974, 559))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(self.widget)
        self.scrollArea.setMinimumSize(QtCore.QSize(394, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 444, 509))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.c1_label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.c1_label.setObjectName("c1_label")
        self.verticalLayout_2.addWidget(self.c1_label)
        self.c1_spinbox = QtWidgets.QSpinBox(self.scrollAreaWidgetContents)
        self.c1_spinbox.setMinimum(50)
        self.c1_spinbox.setMaximum(1500)
        self.c1_spinbox.setProperty("value", 135)
        self.c1_spinbox.setObjectName("c1_spinbox")
        self.verticalLayout_2.addWidget(self.c1_spinbox)
        self.signal_properties_groupbox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.signal_properties_groupbox.setObjectName("signal_properties_groupbox")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.signal_properties_groupbox)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.sampling_frequency_label = QtWidgets.QLabel(self.signal_properties_groupbox)
        self.sampling_frequency_label.setObjectName("sampling_frequency_label")
        self.gridLayout_6.addWidget(self.sampling_frequency_label, 4, 0, 1, 1)
        self.noise_label = QtWidgets.QLabel(self.signal_properties_groupbox)
        self.noise_label.setObjectName("noise_label")
        self.gridLayout_6.addWidget(self.noise_label, 2, 0, 1, 1)
        self.simulation_line_edit = QtWidgets.QLineEdit(self.signal_properties_groupbox)
        self.simulation_line_edit.setObjectName("simulation_line_edit")
        self.gridLayout_6.addWidget(self.simulation_line_edit, 1, 0, 1, 1)
        self.duration_label = QtWidgets.QLabel(self.signal_properties_groupbox)
        self.duration_label.setObjectName("duration_label")
        self.gridLayout_6.addWidget(self.duration_label, 6, 0, 1, 1)
        self.duration_spinbox = QtWidgets.QDoubleSpinBox(self.signal_properties_groupbox)
        self.duration_spinbox.setMinimum(10.0)
        self.duration_spinbox.setMaximum(1000.0)
        self.duration_spinbox.setObjectName("duration_spinbox")
        self.gridLayout_6.addWidget(self.duration_spinbox, 7, 0, 1, 1)
        self.noise_double_spinbox = QtWidgets.QDoubleSpinBox(self.signal_properties_groupbox)
        self.noise_double_spinbox.setObjectName("noise_double_spinbox")
        self.gridLayout_6.addWidget(self.noise_double_spinbox, 3, 0, 1, 1)
        self.signal_name_label = QtWidgets.QLabel(self.signal_properties_groupbox)
        self.signal_name_label.setObjectName("signal_name_label")
        self.gridLayout_6.addWidget(self.signal_name_label, 0, 0, 1, 1)
        self.sampling_frequency_spinbox = QtWidgets.QSpinBox(self.signal_properties_groupbox)
        self.sampling_frequency_spinbox.setMinimum(10)
        self.sampling_frequency_spinbox.setMaximum(1000)
        self.sampling_frequency_spinbox.setSingleStep(1)
        self.sampling_frequency_spinbox.setProperty("value", 100)
        self.sampling_frequency_spinbox.setObjectName("sampling_frequency_spinbox")
        self.gridLayout_6.addWidget(self.sampling_frequency_spinbox, 5, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.signal_properties_groupbox)
        self.preview_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.preview_button.setObjectName("preview_button")
        self.verticalLayout_2.addWidget(self.preview_button)
        self.reset_signal_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.reset_signal_button.setAutoDefault(False)
        self.reset_signal_button.setObjectName("reset_signal_button")
        self.verticalLayout_2.addWidget(self.reset_signal_button)
        self.create_signal_button = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.create_signal_button.setAutoDefault(False)
        self.create_signal_button.setObjectName("create_signal_button")
        self.verticalLayout_2.addWidget(self.create_signal_button)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout.addWidget(self.widget)
        self.plot = PlotWidget(Dialog)
        self.plot.setObjectName("plot")
        self.horizontalLayout.addWidget(self.plot)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.c1_label.setText(_translate("Dialog", "C1"))
        self.signal_properties_groupbox.setTitle(_translate("Dialog", "Signal Properties"))
        self.sampling_frequency_label.setText(_translate("Dialog", "Sampling Frequency"))
        self.noise_label.setText(_translate("Dialog", "Noise (Mean Value)"))
        self.simulation_line_edit.setPlaceholderText(_translate("Dialog", "Simulation Example"))
        self.duration_label.setText(_translate("Dialog", "Duration (s)"))
        self.signal_name_label.setText(_translate("Dialog", "Signal Name"))
        self.preview_button.setText(_translate("Dialog", "Preview Signal"))
        self.reset_signal_button.setText(_translate("Dialog", "Reset Signal"))
        self.create_signal_button.setText(_translate("Dialog", "Create Signal"))

from pyqtgraph import PlotWidget
