# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PycharmProjects/SensoMatrix/ui/fir_filter_designer.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1182, 767)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.groupBox_4 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.band_edges_label = QtWidgets.QLabel(self.groupBox_4)
        self.band_edges_label.setObjectName("band_edges_label")
        self.gridLayout_6.addWidget(self.band_edges_label, 2, 0, 1, 1)
        self.taps_label = QtWidgets.QLabel(self.groupBox_4)
        self.taps_label.setObjectName("taps_label")
        self.gridLayout_6.addWidget(self.taps_label, 1, 0, 1, 1)
        self.ideal_gain_coefficients_label = QtWidgets.QLabel(self.groupBox_4)
        self.ideal_gain_coefficients_label.setObjectName("ideal_gain_coefficients_label")
        self.gridLayout_6.addWidget(self.ideal_gain_coefficients_label, 3, 0, 1, 1)
        self.band_edges_line_edit = QtWidgets.QLineEdit(self.groupBox_4)
        self.band_edges_line_edit.setObjectName("band_edges_line_edit")
        self.gridLayout_6.addWidget(self.band_edges_line_edit, 2, 1, 1, 1)
        self.ideal_gain_coefficients_line_edit = QtWidgets.QLineEdit(self.groupBox_4)
        self.ideal_gain_coefficients_line_edit.setObjectName("ideal_gain_coefficients_line_edit")
        self.gridLayout_6.addWidget(self.ideal_gain_coefficients_line_edit, 3, 1, 1, 1)
        self.taps_line_edit = QtWidgets.QLineEdit(self.groupBox_4)
        self.taps_line_edit.setObjectName("taps_line_edit")
        self.gridLayout_6.addWidget(self.taps_line_edit, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 4, 0, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.channel_list_view = QtWidgets.QListView(self.groupBox_5)
        self.channel_list_view.setObjectName("channel_list_view")
        self.horizontalLayout_2.addWidget(self.channel_list_view)
        self.gridLayout_2.addWidget(self.groupBox_5, 5, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.channel_combo_box = QtWidgets.QComboBox(self.groupBox)
        self.channel_combo_box.setObjectName("channel_combo_box")
        self.gridLayout_3.addWidget(self.channel_combo_box, 0, 1, 1, 1)
        self.channel_label = QtWidgets.QLabel(self.groupBox)
        self.channel_label.setObjectName("channel_label")
        self.gridLayout_3.addWidget(self.channel_label, 0, 0, 1, 1)
        self.sampling_frequency_label = QtWidgets.QLabel(self.groupBox)
        self.sampling_frequency_label.setObjectName("sampling_frequency_label")
        self.gridLayout_3.addWidget(self.sampling_frequency_label, 1, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.least_squares_radio = QtWidgets.QRadioButton(self.groupBox_3)
        self.least_squares_radio.setChecked(True)
        self.least_squares_radio.setObjectName("least_squares_radio")
        self.horizontalLayout.addWidget(self.least_squares_radio)
        self.parks_mcclellan_radio = QtWidgets.QRadioButton(self.groupBox_3)
        self.parks_mcclellan_radio.setObjectName("parks_mcclellan_radio")
        self.horizontalLayout.addWidget(self.parks_mcclellan_radio)
        self.gridLayout_2.addWidget(self.groupBox_3, 3, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(Dialog)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.passband_ripple_label = QtWidgets.QLabel(self.groupBox_2)
        self.passband_ripple_label.setObjectName("passband_ripple_label")
        self.gridLayout_5.addWidget(self.passband_ripple_label, 0, 0, 1, 1)
        self.passband_edge_label = QtWidgets.QLabel(self.groupBox_2)
        self.passband_edge_label.setObjectName("passband_edge_label")
        self.gridLayout_5.addWidget(self.passband_edge_label, 8, 0, 1, 1)
        self.stopband_edge_label = QtWidgets.QLabel(self.groupBox_2)
        self.stopband_edge_label.setObjectName("stopband_edge_label")
        self.gridLayout_5.addWidget(self.stopband_edge_label, 9, 0, 1, 1)
        self.sampling_frequency_label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.sampling_frequency_label_2.setObjectName("sampling_frequency_label_2")
        self.gridLayout_5.addWidget(self.sampling_frequency_label_2, 6, 0, 2, 1)
        self.sampling_frequency_line_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.sampling_frequency_line_edit.setObjectName("sampling_frequency_line_edit")
        self.gridLayout_5.addWidget(self.sampling_frequency_line_edit, 7, 1, 1, 1)
        self.stopband_rejection_line_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.stopband_rejection_line_edit.setObjectName("stopband_rejection_line_edit")
        self.gridLayout_5.addWidget(self.stopband_rejection_line_edit, 4, 1, 1, 1)
        self.passband_ripple_line_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.passband_ripple_line_edit.setObjectName("passband_ripple_line_edit")
        self.gridLayout_5.addWidget(self.passband_ripple_line_edit, 0, 1, 1, 1)
        self.passband_edge_line_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.passband_edge_line_edit.setObjectName("passband_edge_line_edit")
        self.gridLayout_5.addWidget(self.passband_edge_line_edit, 8, 1, 1, 1)
        self.stopband_edge_line_edit = QtWidgets.QLineEdit(self.groupBox_2)
        self.stopband_edge_line_edit.setObjectName("stopband_edge_line_edit")
        self.gridLayout_5.addWidget(self.stopband_edge_line_edit, 9, 1, 1, 1)
        self.stopband_rejection_label = QtWidgets.QLabel(self.groupBox_2)
        self.stopband_rejection_label.setObjectName("stopband_rejection_label")
        self.gridLayout_5.addWidget(self.stopband_rejection_label, 4, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.preview_output_button = QtWidgets.QPushButton(Dialog)
        self.preview_output_button.setEnabled(False)
        self.preview_output_button.setAutoDefault(False)
        self.preview_output_button.setObjectName("preview_output_button")
        self.gridLayout_2.addWidget(self.preview_output_button, 6, 6, 1, 1)
        self.filter_graphics_view = PlotWidget(Dialog)
        self.filter_graphics_view.setObjectName("filter_graphics_view")
        self.gridLayout_2.addWidget(self.filter_graphics_view, 0, 1, 3, 8)
        self.signal_filter_graphics_view = PlotWidget(Dialog)
        self.signal_filter_graphics_view.setObjectName("signal_filter_graphics_view")
        self.gridLayout_2.addWidget(self.signal_filter_graphics_view, 3, 1, 3, 8)
        self.apply_filter_button = QtWidgets.QPushButton(Dialog)
        self.apply_filter_button.setEnabled(False)
        self.apply_filter_button.setAutoDefault(False)
        self.apply_filter_button.setObjectName("apply_filter_button")
        self.gridLayout_2.addWidget(self.apply_filter_button, 6, 8, 1, 1)
        self.save_to_file_button = QtWidgets.QPushButton(Dialog)
        self.save_to_file_button.setAutoDefault(False)
        self.save_to_file_button.setObjectName("save_to_file_button")
        self.gridLayout_2.addWidget(self.save_to_file_button, 6, 7, 1, 1)
        self.estimate_taps_button = QtWidgets.QPushButton(Dialog)
        self.estimate_taps_button.setObjectName("estimate_taps_button")
        self.gridLayout_2.addWidget(self.estimate_taps_button, 2, 0, 1, 1)
        self.design_filter_button = QtWidgets.QPushButton(Dialog)
        self.design_filter_button.setAutoDefault(False)
        self.design_filter_button.setObjectName("design_filter_button")
        self.gridLayout_2.addWidget(self.design_filter_button, 6, 5, 1, 1)
        self.gridLayout_2.setColumnStretch(4, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "FIR Filter Designer"))
        self.groupBox_4.setTitle(_translate("Dialog", "4. Design Parameters"))
        self.band_edges_label.setText(_translate("Dialog", "Band Edges:"))
        self.taps_label.setText(_translate("Dialog", "Taps:"))
        self.ideal_gain_coefficients_label.setText(_translate("Dialog", "Ideal Gain Coefficients:"))
        self.band_edges_line_edit.setText(_translate("Dialog", "0 16 18 100"))
        self.ideal_gain_coefficients_line_edit.setText(_translate("Dialog", "1 1 0 0"))
        self.groupBox_5.setTitle(_translate("Dialog", "5. Apply Filter"))
        self.groupBox.setTitle(_translate("Dialog", "1. Input Channel"))
        self.channel_label.setText(_translate("Dialog", "Channel:"))
        self.sampling_frequency_label.setText(_translate("Dialog", "fs:200 Hz"))
        self.groupBox_3.setTitle(_translate("Dialog", "3. Filter Realization"))
        self.least_squares_radio.setText(_translate("Dialog", "Least-Squares"))
        self.parks_mcclellan_radio.setText(_translate("Dialog", "Parks-McClellan"))
        self.groupBox_2.setTitle(_translate("Dialog", "2. Design Specifications"))
        self.passband_ripple_label.setText(_translate("Dialog", "Passband Ripple (dB): ± "))
        self.passband_edge_label.setText(_translate("Dialog", "Passband Edge (Hz):"))
        self.stopband_edge_label.setText(_translate("Dialog", "Stopband Edge (Hz):"))
        self.sampling_frequency_label_2.setText(_translate("Dialog", "Sampling Frequency (Hz):"))
        self.sampling_frequency_line_edit.setText(_translate("Dialog", "200"))
        self.stopband_rejection_line_edit.setText(_translate("Dialog", "60"))
        self.passband_ripple_line_edit.setText(_translate("Dialog", "0.2"))
        self.passband_edge_line_edit.setText(_translate("Dialog", "16"))
        self.stopband_edge_line_edit.setText(_translate("Dialog", "18"))
        self.stopband_rejection_label.setText(_translate("Dialog", "Stopband Rejection (dB): -"))
        self.preview_output_button.setText(_translate("Dialog", "Preview Output"))
        self.apply_filter_button.setText(_translate("Dialog", "Apply Filter"))
        self.save_to_file_button.setText(_translate("Dialog", "Save filter to file"))
        self.estimate_taps_button.setText(_translate("Dialog", "Estimate Taps"))
        self.design_filter_button.setText(_translate("Dialog", "Design Filter"))

from pyqtgraph import PlotWidget
