"""empty message

Revision ID: 0c9907f7ae13
Revises: f43c7cd39223
Create Date: 2019-07-12 15:17:43.402216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c9907f7ae13'
down_revision = 'f43c7cd39223'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data', 'signal_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('data', 'signal_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
