"""empty message

Revision ID: 709e58afe275
Revises: 214c12c6acba
Create Date: 2019-07-22 20:12:53.651526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709e58afe275'
down_revision = '214c12c6acba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recording',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instituition', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('time_description', sa.String(), nullable=True),
    sa.Column('visit_num', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recording')
    # ### end Alembic commands ###
